"""empty message

Revision ID: 02d1ed775450
Revises: 8e5c871849a9
Create Date: 2024-08-28 23:07:43.396380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d1ed775450'
down_revision = '8e5c871849a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_at_purchase', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_packages', schema=None) as batch_op:
        batch_op.drop_column('price_at_purchase')

    # ### end Alembic commands ###
