"""Adds per head columns

Revision ID: 3a13c2fe492b
Revises: 9ab286847f70
Create Date: 2024-08-28 10:34:21.996670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a13c2fe492b'
down_revision = '9ab286847f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_head', sa.Boolean(), nullable=True))

    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('guest_number')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('per_head')

    # ### end Alembic commands ###
