"""Adds description

Revision ID: 8e5c871849a9
Revises: 3a13c2fe492b
Create Date: 2024-08-28 10:51:22.419754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5c871849a9'
down_revision = '3a13c2fe492b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('party_packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('party_packages', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
